"""
evaluate_batch1_only_models.py

Reads results from model search scripts, identifies best models,
and writes firm_held_out summary CSVs.

Inputs (already generated by model search scripts):
  presence_model_comparison_cv.csv
  aggressive_detector_model_comparison_cv.csv

Outputs:
  firm_held_out_presence_results.csv
  firm_held_out_aggressive_results.csv

Also writes:
  presence_cv_threshold_sensitivity.csv   (CV-based OOF threshold sweep for best presence model)

NOTE: All thresholds are based on OOF predictions. No in-sample threshold selection.
"""

from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

PYPACKAGES = Path("/home/user/.local/pypackages")
if str(PYPACKAGES) not in sys.path:
    sys.path.insert(0, str(PYPACKAGES))

import numpy as np
from sklearn.calibration import CalibratedClassifierCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.metrics import (
    f1_score, precision_score, recall_score, roc_auc_score,
    average_precision_score,
)
from sklearn.model_selection import StratifiedKFold
from sklearn.naive_bayes import ComplementNB
from sklearn.pipeline import FeatureUnion, Pipeline
from sklearn.svm import LinearSVC

ROOT = Path(__file__).resolve().parents[4]
CI = ROOT / "20260618expand" / "classifier_improvement"
B1 = CI / "batch1_only_improvement"
DATA_DIR = B1 / "data"
RES_DIR = B1 / "results"

IN_PRESENCE_DATA = DATA_DIR / "batch1_presence_training_data.csv"
IN_AGG_DATA      = DATA_DIR / "batch1_aggressive_detector_training_data.csv"
IN_PRES_CV       = RES_DIR / "presence_model_comparison_cv.csv"
IN_AGG_CV        = RES_DIR / "aggressive_detector_model_comparison_cv.csv"

OUT_FH_PRESENCE  = RES_DIR / "firm_held_out_presence_results.csv"
OUT_FH_AGG       = RES_DIR / "firm_held_out_aggressive_results.csv"
OUT_PRES_THRESH  = RES_DIR / "presence_cv_threshold_sensitivity.csv"

RANDOM_STATE = 42
N_SPLITS = 5
TARGET_PRECISION = 0.60
TARGET_RECALL = 0.20


def preprocess(text: str) -> str:
    text = re.sub(r"https?://\S+", "<URL>", text)
    text = re.sub(r"@\w+", "<MENTION>", text)
    text = re.sub(r"#(\w+)", r"\1", text)
    return re.sub(r"\s+", " ", text.lower()).strip()


def rebuild_pipeline(model_id: str) -> Pipeline | None:
    """Reconstruct pipeline from model_id string."""
    parts = model_id.split("__")
    if len(parts) != 2:
        return None
    vec_name, clf_name = parts
    RS = RANDOM_STATE

    # Vectorizer
    if vec_name == "word_12_5k":
        vec = TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=5000,
                              min_df=2, max_df=0.95, sublinear_tf=True)
    elif vec_name == "word_12_10k":
        vec = TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=10000,
                              min_df=2, max_df=0.95, sublinear_tf=True)
    elif vec_name == "word_13_5k":
        vec = TfidfVectorizer(analyzer="word", ngram_range=(1,3), max_features=5000,
                              min_df=2, max_df=0.95, sublinear_tf=True)
    elif vec_name == "word_12_md1":
        vec = TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=5000,
                              min_df=1, max_df=0.95, sublinear_tf=True)
    elif vec_name == "char_35_5k":
        vec = TfidfVectorizer(analyzer="char_wb", ngram_range=(3,5), max_features=5000,
                              min_df=2, max_df=0.95, sublinear_tf=True)
    elif vec_name == "word_char_comb":
        vec = FeatureUnion([
            ("word", TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=5000,
                                     min_df=2, max_df=0.95, sublinear_tf=True)),
            ("char", TfidfVectorizer(analyzer="char_wb", ngram_range=(3,5), max_features=5000,
                                     min_df=2, max_df=0.95, sublinear_tf=True)),
        ])
    # Aggressive detector vectorizer variants
    elif vec_name == "word_12_5k" and "agg" in model_id:
        vec = TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=5000,
                              min_df=1, max_df=0.98, sublinear_tf=True)
    elif vec_name == "word_12_10k" and "agg" in model_id:
        vec = TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=10000,
                              min_df=1, max_df=0.98, sublinear_tf=True)
    elif vec_name == "word_13_5k" and "agg" in model_id:
        vec = TfidfVectorizer(analyzer="word", ngram_range=(1,3), max_features=5000,
                              min_df=1, max_df=0.98, sublinear_tf=True)
    elif vec_name == "char_35_5k" and "agg" in model_id:
        vec = TfidfVectorizer(analyzer="char_wb", ngram_range=(3,5), max_features=5000,
                              min_df=1, max_df=0.98, sublinear_tf=True)
    elif vec_name == "word_char_comb" and "agg" in model_id:
        vec = FeatureUnion([
            ("word", TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=5000,
                                     min_df=1, max_df=0.98, sublinear_tf=True)),
            ("char", TfidfVectorizer(analyzer="char_wb", ngram_range=(3,5), max_features=3000,
                                     min_df=1, max_df=0.98, sublinear_tf=True)),
        ])
    else:
        # Generic fallback
        vec = TfidfVectorizer(analyzer="word", ngram_range=(1,2), max_features=5000,
                              min_df=2, max_df=0.95, sublinear_tf=True)

    # Classifier
    if clf_name == "lr_liblin_bal":
        clf = LogisticRegression(class_weight="balanced", solver="liblinear",
                                 C=1.0, max_iter=2000, random_state=RS)
    elif clf_name == "lr_lbfgs_bal":
        clf = LogisticRegression(class_weight="balanced", solver="lbfgs",
                                 C=1.0, max_iter=2000, random_state=RS)
    elif clf_name == "lr_liblin_C01":
        clf = LogisticRegression(class_weight="balanced", solver="liblinear",
                                 C=0.1, max_iter=2000, random_state=RS)
    elif clf_name == "lr_liblin_C10":
        clf = LogisticRegression(class_weight="balanced", solver="liblinear",
                                 C=10.0, max_iter=2000, random_state=RS)
    elif clf_name == "lr_liblin_C5":
        clf = LogisticRegression(class_weight="balanced", solver="liblinear",
                                 C=5.0, max_iter=2000, random_state=RS)
    elif clf_name == "svc_cal_bal":
        clf = CalibratedClassifierCV(
            LinearSVC(class_weight="balanced", max_iter=2000, random_state=RS), cv=3)
    elif clf_name == "cnb":
        clf = ComplementNB(alpha=0.1)
    elif clf_name == "sgd_log":
        clf = SGDClassifier(loss="log_loss", class_weight="balanced",
                            random_state=RS, max_iter=1000)
    elif clf_name == "sgd_log_bal":
        clf = SGDClassifier(loss="log_loss", class_weight="balanced",
                            random_state=RS, max_iter=1000, n_iter_no_change=20)
    else:
        return None

    return Pipeline([("vec", vec), ("clf", clf)])


def oof_proba_collect(pipeline: Pipeline, texts: list[str],
                      labels: list[int], cv: StratifiedKFold) -> np.ndarray:
    oof_proba = np.full(len(labels), np.nan)
    y_arr = np.array(labels)
    for tr_idx, va_idx in cv.split(texts, y_arr):
        X_tr = [texts[i] for i in tr_idx]
        X_va = [texts[i] for i in va_idx]
        pipeline.fit(X_tr, y_arr[tr_idx].tolist())
        if hasattr(pipeline, "predict_proba"):
            oof_proba[va_idx] = pipeline.predict_proba(X_va)[:, 1]
        else:
            df = pipeline.decision_function(X_va)
            oof_proba[va_idx] = (df - df.min()) / (df.ptp() + 1e-9)
    return oof_proba


def firm_held_out_presence(pipeline: Pipeline, texts: list[str],
                           labels: list[int], companies: list[str]) -> list[dict]:
    unique_firms = sorted(set(companies))
    rows = []
    for firm in unique_firms:
        tr_idx = [i for i, c in enumerate(companies) if c != firm]
        va_idx = [i for i, c in enumerate(companies) if c == firm]
        if not va_idx:
            continue
        y_tr = [labels[i] for i in tr_idx]
        y_va = [labels[i] for i in va_idx]
        if len(set(y_tr)) < 2:
            continue
        X_tr = [texts[i] for i in tr_idx]
        X_va = [texts[i] for i in va_idx]
        pipeline.fit(X_tr, y_tr)
        preds = pipeline.predict(X_va)
        rows.append({
            "company_name": firm,
            "n_posts": len(va_idx),
            "n_humor_actual": sum(y_va),
            "f1": round(float(f1_score(y_va, preds, zero_division=0)), 4),
            "precision": round(float(precision_score(y_va, preds, zero_division=0)), 4),
            "recall": round(float(recall_score(y_va, preds, zero_division=0)), 4),
        })
    return rows


def firm_held_out_agg(pipeline: Pipeline, texts: list[str],
                      labels: list[int], companies: list[str]) -> list[dict]:
    unique_firms = sorted(set(companies))
    rows = []
    for firm in unique_firms:
        tr_idx = [i for i, c in enumerate(companies) if c != firm]
        va_idx = [i for i, c in enumerate(companies) if c == firm]
        if not va_idx:
            continue
        y_va = [labels[i] for i in va_idx]
        y_tr = [labels[i] for i in tr_idx]
        if len(set(y_tr)) < 2:
            continue
        n_agg_va = sum(y_va)
        X_tr = [texts[i] for i in tr_idx]
        X_va = [texts[i] for i in va_idx]
        pipeline.fit(X_tr, y_tr)
        preds = pipeline.predict(X_va)
        rows.append({
            "company_name": firm,
            "n_humor_posts": len(va_idx),
            "n_aggressive_actual": n_agg_va,
            "has_aggressive": "yes" if n_agg_va > 0 else "no",
            "precision": round(float(precision_score(y_va, preds, zero_division=0)), 4),
            "recall": round(float(recall_score(y_va, preds, zero_division=0)), 4),
            "f1": round(float(f1_score(y_va, preds, zero_division=0)), 4),
        })
    return rows


def main() -> None:
    print("=== evaluate_batch1_only_models ===")

    # --- Presence best model ---
    if not IN_PRES_CV.exists():
        raise FileNotFoundError(f"Run run_batch1_presence_model_search.py first: {IN_PRES_CV}")
    with open(IN_PRES_CV, encoding="utf-8") as f:
        pres_rows = list(csv.DictReader(f))

    ok_pres = [r for r in pres_rows if r.get("status") == "OK"]
    ok_pres.sort(key=lambda x: float(x.get("oof_auc", 0) or 0), reverse=True)
    best_pres = ok_pres[0] if ok_pres else None

    if best_pres:
        print(f"  Best presence model: {best_pres['model_id']}  OOF AUC={best_pres['oof_auc']}")
        pipe = rebuild_pipeline(best_pres["model_id"])
        if pipe:
            with open(IN_PRESENCE_DATA, encoding="utf-8") as f:
                prows = list(csv.DictReader(f))
            texts = [preprocess(r["text"]) for r in prows]
            labels = [int(r["humor_label"]) for r in prows]
            companies = [r["company_name"] for r in prows]

            # Firm-held-out
            fh_rows = firm_held_out_presence(pipe, texts, labels, companies)
            if fh_rows:
                mean_f1 = round(float(np.mean([r["f1"] for r in fh_rows])), 4)
                mean_prec = round(float(np.mean([r["precision"] for r in fh_rows])), 4)
                mean_rec = round(float(np.mean([r["recall"] for r in fh_rows])), 4)
                print(f"  Firm-held-out presence: mean F1={mean_f1}  prec={mean_prec}  rec={mean_rec}  ({len(fh_rows)} firms)")

                summary_row = {
                    "company_name": "MEAN_ACROSS_FIRMS",
                    "n_posts": sum(r["n_posts"] for r in fh_rows),
                    "n_humor_actual": sum(r["n_humor_actual"] for r in fh_rows),
                    "f1": mean_f1,
                    "precision": mean_prec,
                    "recall": mean_rec,
                }
                out_rows = [summary_row] + fh_rows
                for r in out_rows:
                    r["model_id"] = best_pres["model_id"]
                    r["eval_mode"] = "firm_held_out_all_firms"
                    r["oof_auc_ref"] = best_pres.get("oof_auc", "")

                RES_DIR.mkdir(parents=True, exist_ok=True)
                keys = ["model_id", "eval_mode", "oof_auc_ref", "company_name",
                        "n_posts", "n_humor_actual", "f1", "precision", "recall"]
                with open(OUT_FH_PRESENCE, "w", encoding="utf-8", newline="") as f:
                    w = csv.DictWriter(f, fieldnames=keys, extrasaction="ignore")
                    w.writeheader()
                    w.writerows(out_rows)
                print(f"  Written: {OUT_FH_PRESENCE}")

            # OOF threshold sensitivity for best presence model (CV-based)
            cv = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)
            oof_p = oof_proba_collect(pipe, texts, labels, cv)
            y_arr = np.array(labels)
            valid = ~np.isnan(oof_p)
            thresh_rows = []
            for thr in np.arange(0.10, 0.91, 0.05):
                pred = (oof_p[valid] >= thr).astype(int)
                y_v = y_arr[valid]
                prec = float(precision_score(y_v, pred, zero_division=0))
                rec  = float(recall_score(y_v, pred, zero_division=0))
                f1   = float(f1_score(y_v, pred, zero_division=0))
                abstained = int((oof_p[valid] < thr).sum())
                thresh_rows.append({
                    "model_id":    best_pres["model_id"],
                    "threshold":   round(float(thr), 2),
                    "oof_precision": round(prec, 4),
                    "oof_recall":    round(rec, 4),
                    "oof_f1":        round(f1, 4),
                    "n_predicted_humor": int(pred.sum()),
                    "n_abstained":   abstained,
                    "eval_basis":    "oof_5fold_cv (NOT in-sample)",
                })
            with open(OUT_PRES_THRESH, "w", encoding="utf-8", newline="") as f:
                w = csv.DictWriter(f, fieldnames=list(thresh_rows[0].keys()))
                w.writeheader()
                w.writerows(thresh_rows)
            print(f"  Written: {OUT_PRES_THRESH} (CV-based threshold sweep)")

    # --- Aggressive best model ---
    if not IN_AGG_CV.exists():
        raise FileNotFoundError(f"Run run_batch1_aggressive_detector_search.py first: {IN_AGG_CV}")
    with open(IN_AGG_CV, encoding="utf-8") as f:
        agg_rows = list(csv.DictReader(f))

    ok_agg = [r for r in agg_rows if r.get("status") == "OK"]
    ok_agg.sort(key=lambda x: float(x.get("oof_pr_auc", 0) or 0), reverse=True)
    best_agg = ok_agg[0] if ok_agg else None

    if best_agg:
        print(f"  Best agg model: {best_agg['model_id']}  OOF PR-AUC={best_agg['oof_pr_auc']}")
        pipe = rebuild_pipeline(best_agg["model_id"])
        if pipe:
            with open(IN_AGG_DATA, encoding="utf-8") as f:
                arows = list(csv.DictReader(f))
            texts_a = [preprocess(r["text"]) for r in arows]
            labels_a = [int(r["aggressive_label"]) for r in arows]
            companies_a = [r["company_name"] for r in arows]

            fh_rows = firm_held_out_agg(pipe, texts_a, labels_a, companies_a)
            if fh_rows:
                firms_with_agg = [r for r in fh_rows if r["has_aggressive"] == "yes"]
                if firms_with_agg:
                    mean_f1   = round(float(np.mean([r["f1"] for r in firms_with_agg])), 4)
                    mean_prec = round(float(np.mean([r["precision"] for r in firms_with_agg])), 4)
                    mean_rec  = round(float(np.mean([r["recall"] for r in firms_with_agg])), 4)
                    print(f"  Firm-held-out agg (firms with aggressive): "
                          f"prec={mean_prec}  rec={mean_rec}  f1={mean_f1}  ({len(firms_with_agg)} firms)")
                else:
                    mean_f1 = mean_prec = mean_rec = 0.0

                summary_row = {
                    "company_name": "MEAN_FIRMS_WITH_AGGRESSIVE",
                    "n_humor_posts": sum(r["n_humor_posts"] for r in fh_rows),
                    "n_aggressive_actual": sum(r["n_aggressive_actual"] for r in fh_rows),
                    "has_aggressive": f"{len(firms_with_agg)}/{len(fh_rows)} firms",
                    "precision": mean_prec,
                    "recall": mean_rec,
                    "f1": mean_f1,
                }
                out_rows = [summary_row] + fh_rows
                for r in out_rows:
                    r["model_id"] = best_agg["model_id"]
                    r["eval_mode"] = "firm_held_out_all_firms"
                    r["oof_pr_auc_ref"] = best_agg.get("oof_pr_auc", "")
                    r["meets_provisional_fh"] = (
                        "yes" if isinstance(r.get("precision"), float)
                        and r.get("precision", 0) >= TARGET_PRECISION
                        and r.get("recall", 0) >= TARGET_RECALL else "no"
                    )

                keys = ["model_id", "eval_mode", "oof_pr_auc_ref", "company_name",
                        "n_humor_posts", "n_aggressive_actual", "has_aggressive",
                        "precision", "recall", "f1", "meets_provisional_fh"]
                with open(OUT_FH_AGG, "w", encoding="utf-8", newline="") as f:
                    w = csv.DictWriter(f, fieldnames=keys, extrasaction="ignore")
                    w.writeheader()
                    w.writerows(out_rows)
                print(f"  Written: {OUT_FH_AGG}")

    print("=== evaluate_batch1_only_models COMPLETE ===")


if __name__ == "__main__":
    main()
