name: Disabled Append Humor Collection

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Temporarily disabled invalid workflow. Restore valid workflow before collection.'
